# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560be777ce78b2652be00530da4519b49559ec0cf8ee01eac2f7168e02dfb6f1c549dad88ccae9aaa1ee9002b199e71c3c6528abd73a788091c5857a5bd32af9

test:
  secret_key_base: d188eaab7e4939323f1417d4a1f65d4b98a366bd5fb676307a6212edf6e5a8ab7f12386b5cb130c456240dfe7046f5e8f039ca659bc7f3ce30e07bf7026847d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
